# ==============================================================================
# PowerShell Profile - Generated by init.ps1
# ==============================================================================

# ------------------------------------------------------------------------------
# Oh My Posh
# ------------------------------------------------------------------------------
$env:POSH_DISABLE_COMPLETION = "1"
if (Get-Command oh-my-posh -ErrorAction SilentlyContinue) {
    $themePath = "$env:POSH_THEMES_PATH\{{OhMyPoshTheme}}.omp.json"
    $prevEAP = $ErrorActionPreference; $ErrorActionPreference = 'SilentlyContinue'
    if (Test-Path $themePath) {
        oh-my-posh init pwsh --config $themePath | Invoke-Expression
    }
    else {
        oh-my-posh init pwsh | Invoke-Expression
    }
    $ErrorActionPreference = $prevEAP
}

# ------------------------------------------------------------------------------
# Modules
# ------------------------------------------------------------------------------

# posh-git - Git status in prompt
if (-not (Get-Module -Name posh-git) -and (Get-Module -ListAvailable -Name posh-git)) {
    Import-Module posh-git
}

# Terminal-Icons - File/folder icons
if (-not (Get-Module -Name Terminal-Icons) -and (Get-Module -ListAvailable -Name Terminal-Icons)) {
    Import-Module Terminal-Icons
}

# z - Directory jumping
if (-not (Get-Module -Name z) -and (Get-Module -ListAvailable -Name z)) {
    Import-Module z
}

# PSFzf - Fuzzy finder (requires fzf to be installed)
if (-not (Get-Module -Name PSFzf) -and (Get-Command fzf -ErrorAction SilentlyContinue) -and (Get-Module -ListAvailable -Name PSFzf)) {
    Import-Module PSFzf
    Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+f' -PSReadlineChordReverseHistory 'Ctrl+r'
}

# ------------------------------------------------------------------------------
# PSReadLine Configuration
# ------------------------------------------------------------------------------
if (Get-Module -ListAvailable -Name PSReadLine) {
    # Prediction settings (PSReadLine 2.1.0+)
    try {
        Set-PSReadLineOption -PredictionSource History
        Set-PSReadLineOption -PredictionViewStyle ListView
    }
    catch { }

    # Key bindings
    Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
    Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
    Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward

    # Colors (optional - uses theme colors)
    Set-PSReadLineOption -Colors @{
        Command = 'Cyan'
        Parameter = 'DarkCyan'
        String = 'DarkYellow'
    }
}

# ------------------------------------------------------------------------------
# Aliases
# ------------------------------------------------------------------------------
Set-Alias -Name vim -Value nvim -ErrorAction SilentlyContinue
Set-Alias -Name g -Value git -ErrorAction SilentlyContinue
Set-Alias -Name open -Value explorer -ErrorAction SilentlyContinue

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

# Quick navigation
function .. { Set-Location .. }
function ... { Set-Location ..\.. }
function .... { Set-Location ..\..\.. }

# Create and enter directory
function mkcd { param($dir) New-Item -ItemType Directory -Path $dir -Force; Set-Location $dir }

# Quick edit profile
function Edit-Profile { code $PROFILE }

# Reload profile
function Reload-Profile { . $PROFILE }

# Browse Oh My Posh themes interactively
function Get-PoshThemes {
    $themesPath = $env:POSH_THEMES_PATH

    if (-not $themesPath -or -not (Test-Path $themesPath)) {
        $candidates = @(
            "$env:LOCALAPPDATA\Programs\oh-my-posh\themes",
            "$env:ProgramData\chocolatey\lib\oh-my-posh\tools\themes",
            "$env:USERPROFILE\.poshthemes"
        ) | Where-Object { $_ -and (Test-Path $_) }

        $themesPath = $candidates | Select-Object -First 1
        if ($themesPath) {
            $env:POSH_THEMES_PATH = $themesPath
            Write-Host "POSH_THEMES_PATH was unset; using $themesPath" -ForegroundColor DarkGray
        }
    }

    if (-not $themesPath -or -not (Test-Path $themesPath)) {
        Write-Host "Could not locate Oh My Posh themes." -ForegroundColor Red
        Write-Host "Re-run scripts/init.ps1 to download them, or open a new terminal so the profile sets POSH_THEMES_PATH." -ForegroundColor Yellow
        return
    }

    $themes = Get-ChildItem $themesPath -Filter "*.omp.json"
    if ($themes.Count -eq 0) {
        Write-Host "No themes found in $themesPath" -ForegroundColor Red
        return
    }

    Write-Host "Found $($themes.Count) themes in $themesPath" -ForegroundColor Cyan
    foreach ($theme in $themes) {
        Write-Host "`nTheme: " -NoNewline -ForegroundColor Yellow
        Write-Host $theme.BaseName -ForegroundColor White
        oh-my-posh init pwsh --config $theme.FullName | Invoke-Expression
        $choice = Read-Host "Press Enter for next, or 'y' to keep this theme"
        if ($choice -eq 'y') {
            (Get-Content $PROFILE -Raw) -replace '(?<=POSH_THEMES_PATH\\)[^"\\]+(?=\.omp\.json)', $theme.BaseName |
                Set-Content $PROFILE -NoNewline
            Write-Host "Theme '$($theme.BaseName)' saved to profile." -ForegroundColor Green
            return
        }
    }
    Write-Host "`nEnd of themes." -ForegroundColor Cyan
}

# ==============================================================================
# End of Profile
# ==============================================================================
